name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:


jobs:
  build_and_test:
    name: "Run tests on ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # show all errors for each platform (vs. cancel jobs on error)
      matrix:
        os: [ubuntu-latest] #, macos-latest] # TODO: bring back Windows

    steps:
#      - name: Install Linux Deps
#        if: runner.os == 'Linux'
#        run: |
#          sudo apt-get update
#          sudo apt install libasound2-dev libcurl4-openssl-dev libx11-dev libxinerama-dev libxext-dev libfreetype6-dev libwebkit2gtk-4.0-dev libglu1-mesa-dev libsamplerate-dev

      - name: Get latest CMake
        uses: lukka/get-cmake@latest

      - name: Checkout code
        uses: actions/checkout@v2

      - name: CMake Configure
        run: cmake -Bbuild -DCMAKE_BUILD_TYPE=RelWithDebInfo

      - name: CMake Build
        run: cmake --build build --config RelWithDebInfo --parallel

      - name: CMake Test
        run: |
          ctest --test-dir build -C RelWithDebInfo --show-only
          ctest --test-dir build -C RelWithDebInfo -j4 --output-on-failure
